apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-master
        image: jenkins/jenkins:lts-alpine
        ports:
        - containerPort: 8080
      - name: jenkins-slave
        image: jenkins/jnlp-slave
        env:
          -